server:
  port: 8888
spring:
  application:
    name: student-crm
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/student_crm
    username: user
    password: password
  jpa:
      properties:
        hibernate:
          order_inserts: true
          order_updates: true
          #batch_fetch_style: dynamic
          #default_batch_fetch_size: 30
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            batch_size: 100
            fetch_size: 400
            lob:
              non_contextual_creation: true
      show-sql: true
  flyway:
    enabled: true
    schemas: public
logging:
  level:
    root: INFO
    org.acme.custom.logger: WARN